language: python

python:
  - "3.6"

services:
  - docker

branches:
  only:
  - master

env:

  # Packages to build

  - PACKAGE=kallisto
  - PACKAGE=htstream
  - PACKAGE=qfilt
  - PACKAGE=libdivsufsort
  - PACKAGE=lambda
  - PACKAGE=fuma

before_install:

  # Install Miniconda
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no

  - pip uninstall -y setuptools
  - conda install setuptools

  - conda update -q conda
  - conda info -a
  - conda config --add channels conda-forge
  - conda config --add channels bioconda

install:

  # Create conda environment with python 3.6
  # Install dependencies into conda environment

  - conda create -q -n test python=$TRAVIS_PYTHON_VERSION bioconda-utils docker-py
  - conda activate test


before_script:

  # Download Bioconda-recipe repository

  - git clone https://github.com/bioconda/bioconda-recipes

  # Install bioconda-recipe-gen

  - python setup.py install

script:
  - travis_wait 60 ./travis/test.sh $PACKAGE