language: python

python:
  - "3.6"

services:
  - docker

env:
  
  # Packages to build

  - PACKAGE=kallisto
  - PACKAGE=htstream
  - PACKAGE=clever-toolkit

before_install:

  # Install Miniconda 

  - wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda3/bin:$PATH
  - conda config --add channels conda-forge
  - conda config --add channels bioconda
  - conda update --yes conda

install:

  # Create conda environment with python 3.6

  - conda create --yes -n test python=3.6
  - source activate test

  # Install dependencies into conda environment

  - conda install --yes bioconda-utils docker-py

before_script:

  # Download Bioconda-recipe repository

  - git clone https://github.com/bioconda/bioconda-recipes

  # Install bioconda-recipe-gen

  - python setup.py install

script:
  - travis_wait 20 ./travis/test.sh $PACKAGE
