package:
    name: kallisto2
    version: 0.45.0

source: 
    url: https://github.com/pachterlab/kallisto/archive/v0.45.0.tar.gz
    sha256:
    
requirements:
    build:
        - {{ compiler('cxx') }}
        - cmake
        - make
    
test:
    commands:
        - kallisto version
