package:
    name: 
    version: 

source: 
    url: 
    sha256:
    
requirements:
    build:
        - {{ compiler('cxx') }}
        - cmake
        - make
    
test:
    commands:
        - kallisto version
